### ISSUE TITLE
Unable to make a github release

### ISSUE THREAD

**Issue by WFPhantom** [NillerMedDild/ModpackUploader#32] opened 2023-02-25 13:47 UTC
### Describe your suggestion

First of all sorry for using the general suggestion template i just wasnt sure what else to use.
Running the script produces this error: https://pastebin.com/XMPnUbXn and it doesnt make a github release.

### Why would you like this added/changed?

.

**Comment by NielsPilgaard** [comment] 2023-02-25 17:37
The issue is that the `$MODPACK_VERSION` that you defined in the `settings.ps1` file is not a valid tag - I'm curious, what is it set to? 😄

**Comment by WFPhantom** [comment] 2023-02-25 18:17
That's interesting 
I have it set to `$MODPACK_VERSION = "0.2.3"`

**Comment by NielsPilgaard** [comment] 2023-02-25 19:47
That is.. strange 😄 does that tag already exist in your repo?

**Comment by WFPhantom** [comment] 2023-02-25 19:49
No, i don't think so at least? my repo consists of a Readme.md and a modlist.md that was generated from the modpackuploader and I uploaded manually.

**Comment by NielsPilgaard** [comment] 2023-02-25 19:56
Can you link your repo?

**Comment by WFPhantom** [comment] 2023-02-25 19:56
Yeah i should've done that in the first place
https://github.com/WFPhantom/Balanced-Eternal
edit: Here is my settings.ps1 too https://pastebin.com/hEr14cx1
<blockquote><img src="https://opengraph.githubassets.com/892d8c9ab0113765955effcf8a062afff042f4da8ae8ea2137eea4e0f38902bb/WFPhantom/Balanced-Eternal" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/WFPhantom/Balanced-Eternal">GitHub - WFPhantom/Balanced-Eternal</a></strong></div><div>Contribute to WFPhantom/Balanced-Eternal development by creating an account on GitHub.</div></blockquote>

**Comment by NielsPilgaard** [comment] 2023-02-25 19:58
Ah, I was hoping `settings.ps1` was in there 😅

**Comment by WFPhantom** [comment] 2023-02-25 19:58
i figured, i edited my previous message

**Comment by NielsPilgaard** [comment] 2023-02-25 20:01
Yeah that does look fine - Did your put your GitHub credentials in the `secret.ps1`?

**Comment by WFPhantom** [comment] 2023-02-25 20:03
Yes, my github name, repository and token are all in there, here is my settings.ps1 with the CF and Github tokens removed for obvious reasons https://pastebin.com/JS7yGcD2
Could it be the permissions set up for the token?

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/JS7yGcD2"># Secret settings for the ModpackUploader# For details/help see: https://githu - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by NielsPilgaard** [comment] 2023-02-25 20:05
> Could it be the permissions set up for the token?

Yeaht that might be it.

**Comment by WFPhantom** [comment] 2023-02-25 20:12
Well i gave it all perms and still same error 😅
Edit: Does it need to be a "fine-grained token" the one I'm using is a classic token

**Comment by NielsPilgaard** [comment] 2023-02-25 20:35
I have no idea, I thought there was only one kind :P I'm afraid I don't know what's going on here.

**Comment by WFPhantom** [comment] 2023-02-25 20:37
Assuming it works for the enigmatica modpacks its an issue on my end so I'll just close this issue if u want

**Comment by WFPhantom** [comment] 2023-02-25 21:06
Hi there, i figured i out! my main branch is called main and not master I have no idea why tbf but changing the `target_commitish` in `modpack-uploader.ps1` from master to main fixed it, whoops. Thank you for your help!

**Comment by NielsPilgaard** [comment] 2023-02-25 21:17
Ahh that makes sense, I'll get that fixed on my end, thanks 👍 no reason for it to be hardcoded to `master`

**Comment by NielsPilgaard** [comment] 2023-02-25 21:20
All patched up 👍 

https://github.com/EnigmaticaModpacks/ModpackUploader/releases/tag/2.5.2

<blockquote><img src="https://opengraph.githubassets.com/327e7c20cb40e2b3782f43f8739890e471475f24887b1bae065d2a560a1f056a/EnigmaticaModpacks/ModpackUploader/releases/tag/2.5.2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/EnigmaticaModpacks/ModpackUploader/releases/tag/2.5.2">Release 2.5.2 · EnigmaticaModpacks/ModpackUploader</a></strong></div><div>Full Changelog: 2.5.1...2.5.2</div></blockquote>

**Closed as completed** 2023-02-25 21:20 UTC
Labels: bug
